config/routes.rb
Shmessage::Engine.routes.draw do
  resources :messages

  namespace :api do
    scope module: :v1, default: {format: :json} do
      put 'messages/:id/read', to: 'messages#read'
      resources :messages, only: [:show, :index, :create, :update, :destroy]
    end
  end
end

app/models/shmessage/application_record.rb
module Shmessage
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/shmessage/message.rb
module Shmessage
  class Message < ApplicationRecord
    # 目标角色ids,以_连接
    # :target_role
    mattr_accessor :author_class

    has_many :user_read_messages, class_name: 'Shmessage::UserReadMessage'
    belongs_to :author, class_name: Shmessage.config.author_class

    def self.unread
      result = all
      result = result.includes(:user_read_messages).where(shmessage_user_read_messages: {message_id: nil})
      return result
    end

    def self.create!(args)
      obj = new(args.except(:target_role))
      obj.target_role = args[:target_role].join('_')
      obj.save!
    end

    def update!(args)
      Message.transaction do
        update_attributes(args.except(:target_role))
        self.target_role = args[:target_role].join('_')
        save!
      end
    end

    def has_read_by?(user)
      return !user_read_messages.where(user: user).first.nil?
    end

    def read!(user)
      UserReadMessage.create!(user: user, message: self)
    end

    def target_role
      super.split('_').map {|item| item.to_i}
    end

    private
  end
end

app/models/shmessage/user_read_message.rb
module Shmessage
  class UserReadMessage < ApplicationRecord
    belongs_to :user, class_name: Shmessage.config.user_class
    belongs_to :message, class_name: 'Shmessage::Message'
  end
end

app/controllers/shmessage/api/v1/messages_controller.rb
require_dependency "shmessage/application_controller"

module Shmessage
  module Api
    module V1
      class MessagesController < ::Api::V1::BaseController
        before_action :set_message, only: [:show, :read, :update, :destroy]

        def show
          render json: @message
        end

        def index
          authorize Message
          @messages = policy_scope(Message.all)
          if !params[:unread].blank?
            @messages = @messages.unread
          end
          render json: @messages.order(updated_at: :desc)
        end

        def create
          authorize Message
          @message = Message.create!(message_params.merge(author: current_user))
          render json: @message
        end

        def update
          @message.update!(message_params)
          render json: @message
        end

        def read
          @message.read!(current_user)
          render_success
        end

        def destroy
          @message.destroy!
          render_success
        end

        private

        def set_message
          @message = Message.find_by_id(params[:id])
          if @message
            authorize @message
          else
            skip_authorization
            raise ArgumentError.new('record not found')
          end
        end

        def message_params
          params.require(:message).permit(:title, :body, :target_role => [])
        end
      end
    end
  end
end

app/controllers/shmessage/application_controller.rb
require_dependency "shmessage/application_controller"

module Shmessage
  class ApplicationController < ::ApplicationController
    # protect_from_forgery with: :exception
    # helper Rails.application.routes.url_helpers
  end
end

app/controllers/shmessage/messages_controller.rb
require_dependency "shmessage/application_controller"

module Shmessage
  class MessagesController < ApplicationController
    before_action :set_message, only: [:show, :edit, :update, :destroy]

    # GET /messages
    def index
      authorize Message
      @messages = policy_scope(Message.all)
      if !params[:unread].blank?
        @messages = @messages.unread
      end
      @messages = paginate @messages.order(updated_at: :desc)
    end

    # GET /messages/1
    def show
      authorize @message
    end

    # GET /messages/new
    def new
      authorize Message
      @message = Message.new
    end

    # GET /messages/1/edit
    def edit
      authorize @message
    end

    # POST /messages
    def create
      authorize Message
      @message = Message.new(message_params)

      if @message.save
        redirect_to @message, notice: 'Message was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /messages/1
    def update
      authorize @message
      if @message.update(message_params)
        redirect_to @message, notice: 'Message was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /messages/1
    def destroy
      authorize @message
      @message.destroy
      redirect_to messages_url, notice: 'Message was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:title, :body, :author_id)
    end
  end
end

app/helpers/shmessage/application_helper.rb
module Shmessage
  module ApplicationHelper
  end
end

app/helpers/shmessage/messages_helper.rb
module Shmessage
  module MessagesHelper
  end
end

app/views/layouts/shmessage/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shmessage</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "shmessage/application", media: "all" %>
  <%= javascript_include_tag "shmessage/application" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shmessage/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.number_field :author_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shmessage/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/shmessage/messages/index.html.erb
<div class="col-16 col-md-16 col-lg-16">
  <div class="card">
    <div class="card-header filter-bar">
      <% if policy(Shmessage::Message).new? %>
        <%= link_to shmessage.new_message_path, {class: 'ivu-btn ivu-btn-primary', target: '_blank'} do %>
          <i class="ivu-icon ivu-icon-md-add"></i>
        <% end %>
      <% end %>
    </div>

    <div class="card-body p-0">
      <div class="table-responsive">
        <table class="table table-striped table-md">
          <tbody>
          <tr>
            <th>Title</th>
            <th>Updated</th>
            <th>Has Read</th>
            <% if policy(Shmessage::Message).update? || policy(Shmessage::Message).destroy? || policy(Shmessage::Message).read? %>
              <th>Operation</th>
            <% end %>

          </tr>
          <% @messages.each do |message| %>
            <tr>
              <td><%= message.title %></td>
              <td><%= message.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
              <td><%= message.has_read_by?(current_user) ? 'Yes' : '' %></td>
              <td>
                <% if policy(Shmessage::Message).update? %>
                  <%= link_to shmessage.edit_message_path(message), {class: 'btn btn-icon btn-primary', target: '_blank'} do %>
                    <i class="far fa-edit"></i>
                  <% end %>
                <% end %>
                <% if policy(Shmessage::Message).destroy? %>
                  <%= link_to shmessage.message_path(message), {class: 'btn btn-icon btn-danger', method: :delete, data: {confirm: 'Confirm to Delete?'}} do %>
                    <i class="fas fa-times"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <%= paginate @messages %>
  </div>
</div>

<%# content_for :additional_js do %>
<%#= javascript_pack_tag 'messages_index' %>
<%# end %>

app/views/shmessage/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/shmessage/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @message.author_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>